import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
// @ts-expect-error - build/server/index.js is generated by `npm run build`; no declaration file exists for it.
import * as build from "../build/server/index.js";

export const onRequest: PagesFunction = createPagesFunctionHandler({ build });
